--1. Mostrar todos los usuarios que no han creado ningún tablero, para dichos usuarios mostrar el
--nombre completo y correo, utilizar producto cartesiano con el operador (+).
SELECT * 
FROM TBL_USUARIOS;

SELECT * 
FROM TBL_TABLERO;

SELECT *
FROM TBL_USUARIOS_X_TABLERO;

SELECT  A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_COMPLETO,
        A.CORREO
FROM TBL_USUARIOS A,
TBL_TABLERO B
WHERE A.CODIGO_USUARIO = B.CODIGO_USUARIO_CREA(+) AND B.CODIGO_TABLERO IS NULL; 


--2. Mostrar la cantidad de usuarios que se han registrado por cada red social, mostrar inclusive la
--cantidad de usuarios que no están registrados con redes sociales.

SELECT * 
FROM TBL_REDES_SOCIALES;

SELECT *
FROM TBL_USUARIOS;

SELECT  B.CODIGO_RED_SOCIAL,
        B.NOMBRE_RED_SOCIAL,
        COUNT(A.CODIGO_USUARIO) AS USUARIOS_REGISTRADOS
FROM TBL_USUARIOS A
LEFT JOIN TBL_REDES_SOCIALES B
ON A.CODIGO_RED_SOCIAL = B.CODIGO_RED_SOCIAL
GROUP BY B.CODIGO_RED_SOCIAL, B.NOMBRE_RED_SOCIAL;


--3. Consultar el usuario que ha hecho más comentarios sobre una tarjeta (El más prepotente), para
--este usuario mostrar el nombre completo, correo, cantidad de comentarios y cantidad de
--tarjetas a las que ha comentado (pista: una posible solución para este último campo es utilizar
--count(distinct campo))

SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_COMENTARIOS
FROM TBL_COMENTARIOS
GROUP BY CODIGO_USUARIO;

WITH COMENTARIOS AS (
    SELECT  A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_COMPLETO,
            A.CORREO,
            COUNT(B.CODIGO_COMENTARIO) AS CANTIDAD_COMENTARIOS,
            COUNT(DISTINCT B.CODIGO_TARJETA) AS TARJETAS
    FROM TBL_USUARIOS A
    INNER JOIN TBL_COMENTARIOS B
    ON A.CODIGO_USUARIO = B.CODIGO_USUARIO
    GROUP BY A.NOMBRE || ' ' || A.APELLIDO, A.CORREO
)
SELECT *
FROM COMENTARIOS
WHERE CANTIDAD_COMENTARIOS = (SELECT MAX(CANTIDAD_COMENTARIOS) FROM COMENTARIOS);

COMMIT;

--4. Mostrar TODOS los usuarios con plan FREE, de dichos usuarios mostrar la siguiente información:
--• Nombre completo
--• Correo
--• Red social (En caso de estar registrado con una)
--• Cantidad de organizaciones que ha creado, mostrar 0 si no ha creado ninguna.

SELECT * 
FROM TBL_USUARIOS
WHERE CODIGO_PLAN = 1;

SELECT *
FROM TBL_PLANES;

SELECT *
FROM TBL_ORGANIZACIONES;

SELECT *
FROM TBL_USUARIOS_X_ORGANIZACION;

SELECT  A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_COMPLETO,
        A.CORREO,
        A.CODIGO_RED_SOCIAL,
        C.NOMBRE_RED_SOCIAL,
        B.NOMBRE_PLAN,
        NVL(COUNT(D.CODIGO_ORGANIZACION), 0) AS ORGANIZACIONES_CREADAS
FROM TBL_USUARIOS A
LEFT JOIN TBL_PLANES B
ON A.CODIGO_PLAN = B.CODIGO_PLAN
LEFT JOIN TBL_REDES_SOCIALES C
ON A.CODIGO_RED_SOCIAL = C.CODIGO_RED_SOCIAL
LEFT JOIN TBL_ORGANIZACIONES D
ON A.CODIGO_USUARIO = D.CODIGO_ADMINISTRADOR
WHERE A.CODIGO_PLAN = 1
GROUP BY A.NOMBRE || ' ' || A.APELLIDO, A.CORREO, A.CODIGO_RED_SOCIAL, B.NOMBRE_PLAN, C.NOMBRE_RED_SOCIAL;


--5. Mostrar los usuarios que han creado más de 5 tarjetas, para estos usuarios mostrar:
--Nombre completo, correo, cantidad de tarjetas creadas

--VOY A HACER EL QUE TIENE DOS O MÁS PORQUE QUE PEREZA HACER TRES REGISTROS MÁS PARA UN SOLO USUARIO

SELECT * 
FROM TBL_USUARIOS;

SELECT *
FROM TBL_TARJETAS;

SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_TARJETAS
FROM TBL_TARJETAS
GROUP BY CODIGO_USUARIO;

SELECT  A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_COMPLETO,
        A.CORREO,
        COUNT(B.CODIGO_TARJETA) AS CANTIDAD_TARJETAS
FROM TBL_USUARIOS A
LEFT JOIN TBL_TARJETAS B
ON A.CODIGO_USUARIO = B.CODIGO_USUARIO
HAVING COUNT(B.CODIGO_TARJETA) >= 2
GROUP BY A.NOMBRE || ' ' || A.APELLIDO, A.CORREO;

--6. Un usuario puede estar suscrito a tableros, listas y tarjetas, de tal forma que si hay algún cambio
--se le notifica en su teléfono o por teléfono, sabiendo esto, se necesita mostrar los nombres de
--todos los usuarios con la cantidad de suscripciones de cada tipo, en la consulta se debe mostrar:
--• Nombre completo del usuario
--• Cantidad de tableros a los cuales está suscrito
--• Cantidad de listas a las cuales está suscrito
--• Cantidad de tarjetas a las cuales está suscrito

SELECT * 
FROM TBL_USUARIOS;

SELECT * 
FROM TBL_SUSCRIPCIONES;

SELECT  A.NOMBRE || ' ' || A.APELLIDO AS NOMBRE_COMPLETO,
        COUNT(B.CODIGO_LISTA) AS SUSCRIPCIONES_LISTAS,
        COUNT(B.CODIGO_TABLERO) AS SUSCRIPCIONES_TABLEROS,
        COUNT(B.CODIGO_TARJETA) AS SUSCRIPCIONES_TARJETAS
FROM TBL_USUARIOS A
LEFT JOIN TBL_SUSCRIPCIONES B
ON A.CODIGO_USUARIO = B.CODIGO_USUARIO
GROUP BY A.NOMBRE || ' ' || A.APELLIDO;


--7. Consultar todas las organizaciones con los siguientes datos:
--Nombre de la organización
--Cantidad de usuarios registrados en cada organización
--Cantidad de Tableros por cada organización
--Cantidad de Listas asociadas a cada organización
--Cantidad de Tarjetas asociadas a cada organización

SELECT *
FROM TBL_TIPOS_USUARIO;

SELECT *
FROM TBL_ORGANIZACIONES;

--DE ESTA CONSULTA SACAMOS LA CANTIDAD DE USUARIOS POR ORGANIZACION
SELECT  CODIGO_ORGANIZACION, COUNT(*) AS CANTIDAD_USUARIOS
FROM TBL_USUARIOS_X_ORGANIZACION
GROUP BY CODIGO_ORGANIZACION;

--DE ESTA CONSULTA SACAMOS LA CANTIDAD DE TABLEROS POR ORGANIZACION
SELECT  CODIGO_ORGANIZACION, COUNT(*) AS CANTIDAD_TABLEROS
FROM TBL_TABLERO 
GROUP BY CODIGO_ORGANIZACION;

--DE ESTA CONSULTA SACAMOS LA CANTIDAD DE LISTAS POR ORGANIZACION, UTILIZANDO UN INNER JOIN PARA RELACIONAR TABLERO CON LISTAS Y PODER OBTENER LA CANTIDAD DE LISTAS
SELECT  CODIGO_ORGANIZACION, COUNT(*) AS CANTIDAD_LISTAS
FROM TBL_TABLERO A 
INNER JOIN TBL_LISTAS B
ON A.CODIGO_TABLERO = B.CODIGO_TABLERO
GROUP BY CODIGO_ORGANIZACION;

--DE ESTA CONSULTA SACAMOS LA CANTIDAD DE TARJETAS POR ORGANIZACION, HACIENDO INNER JOINS CON LAS TABLAS TABLERO, LISTAS Y TARJETAS
SELECT  CODIGO_ORGANIZACION, COUNT(*) AS CANTIDAD_TARJETAS
FROM TBL_TABLERO A
INNER JOIN TBL_LISTAS B
ON A.CODIGO_TABLERO = B.CODIGO_TABLERO
INNER JOIN TBL_TARJETAS C
ON B.CODIGO_LISTA = C.CODIGO_LISTA
GROUP BY CODIGO_ORGANIZACION;

WITH USUARIOS_ORGANIZACIONES AS (
    SELECT  CODIGO_ORGANIZACION, COUNT(*) AS CANTIDAD_USUARIOS
    FROM TBL_USUARIOS_X_ORGANIZACION
    GROUP BY CODIGO_ORGANIZACION
), 
TABLEROS_ORGANIZACIONES AS (
    SELECT  CODIGO_ORGANIZACION, COUNT(*) AS CANTIDAD_TABLEROS
    FROM TBL_TABLERO 
    GROUP BY CODIGO_ORGANIZACION
), 
LISTAS_ORGANIZACIONES AS (
    SELECT  CODIGO_ORGANIZACION, COUNT(*) AS CANTIDAD_LISTAS
    FROM TBL_TABLERO A 
    INNER JOIN TBL_LISTAS B
    ON A.CODIGO_TABLERO = B.CODIGO_TABLERO
    GROUP BY CODIGO_ORGANIZACION
),
TARJETAS_ORGANIZACIONES AS (
    SELECT  CODIGO_ORGANIZACION, COUNT(*) AS CANTIDAD_TARJETAS
    FROM TBL_TABLERO A
    INNER JOIN TBL_LISTAS B
    ON A.CODIGO_TABLERO = B.CODIGO_TABLERO
    INNER JOIN TBL_TARJETAS C
    ON B.CODIGO_LISTA = C.CODIGO_LISTA
    GROUP BY CODIGO_ORGANIZACION
)
SELECT  A.CODIGO_ORGANIZACION,
        NVL(B.CANTIDAD_USUARIOS, 0) AS CANTIDAD_USUARIOS,
        NVL(C.CANTIDAD_TABLEROS, 0) AS CANTIDAD_TABLEROS,
        NVL(D.CANTIDAD_LISTAS, 0) AS CANTIDAD_LISTAS,
        NVL(E.CANTIDAD_TARJETAS, 0) AS CANTIDAD_TARJETAS
FROM TBL_ORGANIZACIONES A
LEFT JOIN USUARIOS_ORGANIZACIONES B
ON A.CODIGO_ORGANIZACION = B.CODIGO_ORGANIZACION
LEFT JOIN TABLEROS_ORGANIZACIONES C
ON B.CODIGO_ORGANIZACION = C.CODIGO_ORGANIZACION
LEFT JOIN LISTAS_ORGANIZACIONES D
ON C.CODIGO_ORGANIZACION = D.CODIGO_ORGANIZACION
LEFT JOIN TARJETAS_ORGANIZACIONES E
ON D.CODIGO_ORGANIZACION = E.CODIGO_ORGANIZACION
GROUP BY A.CODIGO_ORGANIZACION, B.CANTIDAD_USUARIOS, C.CANTIDAD_TABLEROS, D.CANTIDAD_LISTAS, E.CANTIDAD_TARJETAS;



--8. Crear una vista materializada con la información de facturación, los campos a incluir son los
--siguientes:
--• Código factura
--• Nombre del plan a facturar
--• Nombre completo del usuario
--• Fecha de pago (Utilizar fecha inicio, mostrarla en formato Día-Mes-Año)
--• Año y Mes de pago (basado en la fecha inicio)
--• Monto de la factura
--• Descuento
--• Total neto