--1. Desarrollar una consulta para encontrar a los 5 usuarios más activos en cuanto a participación en grupos.
--Se considera participación activa cuando un usuario ha publicado contenido en al menos 3 grupos diferentes durante el último año.
--Mostrar el nombre del usuario, la cantidad de grupos en los que publicó, y el total de publicaciones realizadas en esos grupos.

SELECT *
FROM TBL_GRUPOS;

SELECT *
FROM TBL_PUBLICACIONES;
WHERE CODIGO_USUARIO = 1;

SELECT  A.NOMBRE_USUARIO,
        COUNT(B.CODIGO_GRUPO) AS PARTICIPACION_EN_GRUPOS,
        COUNT(B.CODIGO_PUBLICACION) AS CANTIDAD_PUBLICACIONES
FROM TBL_USUARIOS A
INNER JOIN TBL_PUBLICACIONES B
ON A.CODIGO_USUARIO = B.CODIGO_USUARIO
WHERE B.FECHA_PUBLICACION >= '26-MAR-2025'
HAVING COUNT(B.CODIGO_GRUPO) >= 3
GROUP BY A.NOMBRE_USUARIO;

--2. Desarrollar una consulta para obtener las 5 fotos que más interacciones (likes y etiquetas) han recibido en el último año.
--Muestre el título de la foto, el nombre completo del usuario que la subió y el total de interacciones, además mostrar
--el país del usuario, la cantidad de mensajes que ha enviado y la cantidad de mensajes que ha recibido.

SELECT *
FROM TBL_FOTOS;

SELECT *
FROM TBL_LIKE_FOTOGRAFIAS
ORDER BY 2;

SELECT *
FROM TBL_MENSAJES;

--CANTIDAD DE LIKES POR FOTO
SELECT  CODIGO_FOTO,
        COUNT(*) AS CANTIDAD_LIKES
FROM TBL_LIKE_FOTOGRAFIAS
GROUP BY CODIGO_FOTO;

--CANTIDAD DE ETIQUETAS POR FOTOS
SELECT  CODIGO_FOTO,
        COUNT(*) AS CANTIDAD_ETIQUETAS
FROM TBL_ETIQUETA_FOTOGRAFIAS
GROUP BY CODIGO_FOTO;

--USUARIOS QUE HAN SUBIDO FOTOS
SELECT  B.CODIGO_USUARIO,
        C.NOMBRE_USUARIO,
        D.NOMBRE_PAIS,
        A.CODIGO_FOTO
FROM TBL_FOTOS A
INNER JOIN TBL_ALBUMES B
ON A.CODIGO_ALBUM = B.CODIGO_ALBUM
INNER JOIN TBL_USUARIOS C
ON B.CODIGO_USUARIO = C.CODIGO_USUARIO
INNER JOIN TBL_PAISES D
ON C.CODIGO_PAIS = D.CODIGO_PAIS;

--CANTIDAD DE MENSAJES RECIBIDOS
SELECT  A.CODIGO_USUARIO,
        COUNT(*) AS RECIBIDOS
FROM TBL_USUARIOS A 
INNER JOIN TBL_MENSAJES B
ON A.CODIGO_USUARIO = B.CODIGO_USUARIO
GROUP BY A.CODIGO_USUARIO;

--CANTIDAD DE MENSAJES ENVIADOS
SELECT  A.CODIGO_USUARIO,
        COUNT(*) AS ENVIADOS
FROM TBL_USUARIOS A
INNER JOIN TBL_MENSAJES B
ON A.CODIGO_USUARIO = B.CODIGO_REMITENTE
GROUP BY A.CODIGO_USUARIO;

WITH LIKES AS (
    SELECT  CODIGO_FOTO,
            COUNT(*) AS CANTIDAD_LIKES
    FROM TBL_LIKE_FOTOGRAFIAS
    GROUP BY CODIGO_FOTO
),
ETIQUETAS AS (
    SELECT  CODIGO_FOTO,
            COUNT(*) AS CANTIDAD_LIKES
    FROM TBL_LIKE_FOTOGRAFIAS
    GROUP BY CODIGO_FOTO
),
USUARIOS_FOTOS AS (
    SELECT  B.CODIGO_USUARIO,
            C.NOMBRE_USUARIO,
            D.NOMBRE_PAIS,
            A.CODIGO_FOTO,
            A.DESCRIPCION_FOTO
    FROM TBL_FOTOS A
    INNER JOIN TBL_ALBUMES B
    ON A.CODIGO_ALBUM = B.CODIGO_ALBUM
    INNER JOIN TBL_USUARIOS C
    ON B.CODIGO_USUARIO = C.CODIGO_USUARIO
    INNER JOIN TBL_PAISES D
    ON C.CODIGO_PAIS = D.CODIGO_PAIS
),
MENSAJES_ENVIADOS AS (
    SELECT  A.CODIGO_USUARIO,
            COUNT(*) AS ENVIADOS
    FROM TBL_USUARIOS A
    INNER JOIN TBL_MENSAJES B
    ON A.CODIGO_USUARIO = B.CODIGO_REMITENTE
    GROUP BY A.CODIGO_USUARIO
),
MENSAJES_RECIBIDOS AS (
    SELECT  A.CODIGO_USUARIO,
            COUNT(*) AS RECIBIDOS
    FROM TBL_USUARIOS A 
    INNER JOIN TBL_MENSAJES B
    ON A.CODIGO_USUARIO = B.CODIGO_USUARIO
    GROUP BY A.CODIGO_USUARIO
)

